#ifndef SPI_CONFIG_H
#define SPI_CONFIG_H

/* Default SPI Configuration */
#define SPI_DEFAULT_MODE SPI_MASTER
#define SPI_DEFAULT_PRESCALER SPI_CLK_FOSC_64
#define SPI_DEFAULT_POLARITY SPI_CLK_IDLE_LOW
#define SPI_DEFAULT_PHASE SPI_SAMPLE_MIDDLE

#endif
