#ifndef LCD_PRIVATE_H
#define LCD_PRIVATE_H

#define LCD_BACKLIGHT 0x08U
#define LCD_ENABLE 0x04U
#define LCD_READWRITE 0x02U
#define LCD_REGISTERSELECT 0x01U

#define LCD_FUNCTION_SET 0x28U
#define LCD_DISPLAY_OFF 0x08U
#define LCD_CLEAR_DISPLAY 0x01U
#define LCD_ENTRY_MODE 0x06U
#define LCD_DISPLAY_ON 0x0CU

#endif