#ifndef CAR_CONFIG_H
#define CAR_CONFIG_H

#include "../../MCAL/GPIO/GPIO_interface.h"
#include "../../HAL/DC_MOTOR/DC_MOTOR_interface.h"
#include "../../HAL/IR/IR_interface.h"
#include "../../HAL/ULTRASONIC/ULTRASONIC_interface.h"
#include "../../MCAL/PWM/PWM_interface.h"
#include "../../MCAL/UART/UART_interface.h"

#define CAR_DEFAULT_MOTOR_SPEED_PERCENT 60U
#define CAR_HORN_PULSE_MS 80U

#define CAR_LEFT_MOTOR_IN1_PORT GPIO_PORTD
#define CAR_LEFT_MOTOR_IN1_PIN GPIO_PIN0
#define CAR_LEFT_MOTOR_IN2_PORT GPIO_PORTD
#define CAR_LEFT_MOTOR_IN2_PIN GPIO_PIN1
#define CAR_LEFT_MOTOR_EN_PORT GPIO_PORTC
#define CAR_LEFT_MOTOR_EN_PIN GPIO_PIN2
#define CAR_LEFT_MOTOR_PWM_CHANNEL PWM_CHANNEL1

#define CAR_RIGHT_MOTOR_IN1_PORT GPIO_PORTD
#define CAR_RIGHT_MOTOR_IN1_PIN GPIO_PIN2
#define CAR_RIGHT_MOTOR_IN2_PORT GPIO_PORTD
#define CAR_RIGHT_MOTOR_IN2_PIN GPIO_PIN3
#define CAR_RIGHT_MOTOR_EN_PORT GPIO_PORTC
#define CAR_RIGHT_MOTOR_EN_PIN GPIO_PIN1
#define CAR_RIGHT_MOTOR_PWM_CHANNEL PWM_CHANNEL2

#define CAR_FRONT_SENSOR_TRIGGER_PORT GPIO_PORTB
#define CAR_FRONT_SENSOR_TRIGGER_PIN GPIO_PIN4
#define CAR_FRONT_SENSOR_ECHO_PORT GPIO_PORTB
#define CAR_FRONT_SENSOR_ECHO_PIN GPIO_PIN5

#define CAR_BACK_SENSOR_TRIGGER_PORT GPIO_PORTB
#define CAR_BACK_SENSOR_TRIGGER_PIN GPIO_PIN2
#define CAR_BACK_SENSOR_ECHO_PORT GPIO_PORTB
#define CAR_BACK_SENSOR_ECHO_PIN GPIO_PIN3

#define CAR_RIGHT_SENSOR_TRIGGER_PORT GPIO_PORTB
#define CAR_RIGHT_SENSOR_TRIGGER_PIN GPIO_PIN6
#define CAR_RIGHT_SENSOR_ECHO_PORT GPIO_PORTB
#define CAR_RIGHT_SENSOR_ECHO_PIN GPIO_PIN7

#define CAR_LEFT_SENSOR_TRIGGER_PORT GPIO_PORTB
#define CAR_LEFT_SENSOR_TRIGGER_PIN GPIO_PIN0
#define CAR_LEFT_SENSOR_ECHO_PORT GPIO_PORTB
#define CAR_LEFT_SENSOR_ECHO_PIN GPIO_PIN1

#define CAR_TRACK_SENSOR_PORT GPIO_PORTA
#define CAR_TRACK_SENSOR_PIN GPIO_PIN4

#define CAR_RED_LED_PORT GPIO_PORTA
#define CAR_RED_LED_PIN GPIO_PIN0

#define CAR_YELLOW_LED_RIGHT_PORT GPIO_PORTA
#define CAR_YELLOW_LED_RIGHT_PIN GPIO_PIN1

#define CAR_YELLOW_LED_LEFT_PORT GPIO_PORTA
#define CAR_YELLOW_LED_LEFT_PIN GPIO_PIN2

#define CAR_WHITE_LED_PORT GPIO_PORTA
#define CAR_WHITE_LED_PIN GPIO_PIN3

#endif
