#ifndef TIMER0_CONFIG_H
#define TIMER0_CONFIG_H

/* Default Timer0 Configuration */
#define TIMER0_DEFAULT_MODE TIMER0_TIMER_MODE
#define TIMER0_DEFAULT_PRESCALER TIMER0_PRESCALER_256
#define TIMER0_DEFAULT_INT TIMER0_INT_ENABLE

#endif
